---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
---

```{r setup, include=FALSE}
require(flexdashboard)
require(ggExtra)
require(grid)
require(tidyverse)
require(shadowtext)
require(fmsb)
require(plotly)
require(dygraphs)
require(visNetwork)
require(psych)


names <- c("Hantavirus", "Tularemia", "Dengue", "Ebola", "E. coli", 
           "Tuberculosis", "Salmonella", "Vaccinia", "Brucella")
  
data <- data.frame(count = c(6, 7, 7, 9, 11, 15, 17, 18, 54), 
                   name = factor(names, levels = names),
                   y = seq(length(names)) * 0.9)

BLUE  <- "#076fa2"
RED   <- "#E3120B"
BLACK <- "#202020"
GREY  <- "grey50"
  


data2 <- as.data.frame(matrix( sample( 2:20 , 10 , replace=T) , ncol=10))

colnames(data2) <- c("math" , "english" , "biology" , "music" , "R-coding", 
                    "data-viz" , "french" , "physic", "statistic", "sport" )
 
data2 <- rbind(rep(20,10) , rep(0,10) , data2)
 

library(pacman)
p_load(haven, tidyverse, modelsummary, here, ggplot2,dplyr, ggtext, here, sf,  osmdata, tigris, viridis, tidycensus, tmap, elevatr, plotly, flexdashboard, grid, png)

medexam<-read.csv(here('final/MedicalExaminerTableau_2020_05_Migrated Data.csv'))

overall_rate3<- read.csv(here('final/2019-2023.csv'))

map <- st_read(here('/Users/mayacasper/Desktop/EDLD 652/EDLD/final/counties/counties.shp'))

medexam<- medexam %>%
  select(County, Drug.Type,Time.Measure,Count, Time.Period, Rate, Count.rate, Manner)

overall<- medexam %>%
  filter(Drug.Type =='All Drugs') %>%
  filter(County =='OREGON STATEWIDE')
or <- counties(state='41',year=2022)
or$NAME <- toupper(or$NAME)
or <- or %>%
  rename(County = NAME)
  

map <- overall_rate3 %>% 
  filter(Time.Period == 2022) %>%  
filter(County != "OREGON STATEWIDE")

map_plot <- left_join(or, map)

image <- readPNG("/Users/mayacasper/Desktop/Viz6_1.png")
 
```

Sidebar Title {.sidebar}
==========================
Your text here. You can use markdown syntax, including 
[links](http://blah.com), *italics*, **bolding**, etc.


Page 1 {data-icon="fa-list"}
=======================================

Column 
----------------------------------------

### Chart A

This is **typical** .Rmd text.

```{r 1}

counties<-medexam %>%
  filter(Drug.Type =='All Drugs') %>%
  filter(Time.Measure == 'Year') %>%
  filter(Count.rate== 'Rate') 


counties$Time.Period <- as.numeric(counties$Time.Period)

overall_rate2 <- counties %>%
  group_by(County, Time.Period) %>% 
  summarize(Sum_Rate = sum(Rate))
counties <- counties %>%
  left_join(overall_rate2, by = "Time.Period")

overall_rate2<- overall_rate2[-287,]


my_color<-rep('gray',length(unique(overall_rate3$County)))
    names(my_color) <- unique(overall_rate3$County) 
    my_color['OREGON STATEWIDE'] <- 'black' 
    my_color['GILLIAM']<- '#FF9DA7'
    my_color['LANE']<- '#59A14F'
    my_color['MULTNOMAH']<- '#E15759'
    my_color['BAKER']<- '#4E79A7'
    my_color['LINN']<- '#F28E2B'
    my_color['KLAMATH']<- '#9C755F'

finalviz2<- ggplot(overall_rate3,
           aes(x = Time.Period, y = Sum_Rate, colour = County)) +
      geom_line(stat = 'identity') + 
      scale_color_manual(values=my_color) +
      labs(title="There are stark difference in overdose death rates <br /> among Oregon counties",
           subtitle = 'Rates include accidental and suicide overdose deaths',
           x     = '',
           y     = 'Rate per 100,000 deaths',
           caption = "Source: Oregon Prescribing Data Dashboard") +
  theme(plot.title= element_markdown(margin = margin(b=3),hjust=0, size = 15, face ='bold'),
  plot.subtitle= element_markdown(margin = margin(b=30),hjust=0, size = 12, face = 'italic'),
    panel.background = element_rect(fill='white',colour='white'),
    axis.ticks= element_blank(),
    panel.grid.major.y = element_line(color      = "grey80", 
                                              linewidth  = 0.5, 
                                              linetype   = "dashed"),
    plot.caption= element_text(hjust = 0.01,
                               size = 9,
                               margin=margin(t=0)),
    axis.line.x = element_line(color = "black", linewidth = 0.7),
    axis.ticks.x = element_line(color='black',linewidth = .7), 
    axis.ticks.length=unit(.35, "cm"), 
         plot.margin = margin(1, 1,1,1, "cm"),
         legend.position = 'none', 
         axis.title.y = element_markdown(size   = 9, 
                                                  vjust  = 1.05,
                                                  angle  = 360, 
                                                  margin = margin(r = -80,b=0)),) +
      scale_y_continuous(breaks = seq(0, 65, by = 5),
                         limits = c(0,65)) +
      scale_x_continuous(expand = c(0,0),
                         limits = c(2009,2022), 
                         breaks = seq(2010, 2022, by = 2))+ 
      annotate('text',
             x        = 2014,
             y        = 15,
             hjust    = .1,
             vjust    = 0,
             label    = 'Oregon Statewide',
             size     = 4,
             color    = 'black', 
             fontface = 'bold') 
             
ggplotly(finalviz2)

```

### Chart C

```{r 2}

overall_rate4 <- overall_rate3[overall_rate3$County %in% c('GILLIAM', 'LANE', 'MULTNOMAH','BAKER','LINN','KLAMATH'),]

finalviz3 <- ggplot(overall_rate4,
                    aes(x = Time.Period, y = Sum_Rate)) +
  geom_line(stat = 'identity', aes(color = County)) +
  scale_color_manual(values = c('GILLIAM' = '#FF9DA7', 'LANE' = '#59A14F', 'MULTNOMAH' = '#E15759', 'BAKER' = '#4E79A7', 'LINN' = '#F28E2B', 'KLAMATH' = '#9C755F')) +
  labs(title = "There are stark differences in overdose death rates <br />among Oregon counties",
       subtitle = 'Rates include accidental and suicide overdose deaths',
       x = '',
       y = 'Rate per 100,000 deaths',
       caption = "Source: Oregon Prescribing Data Dashboard") +
  theme(plot.title = element_markdown(margin = margin(b = 3), hjust = 0, size = 12, face = 'bold'),
        plot.subtitle = element_markdown(margin = margin(b = 30), hjust = 0, size = 12, face = 'italic'),
        panel.background = element_rect(fill = 'white', colour = 'white'),
        axis.ticks = element_blank(),
        panel.grid.major.y = element_line(color = "grey95", linewidth = 0.5, linetype = "dashed"),
        plot.caption = element_text(hjust = 0.01, size = 9, margin = margin(t = 0)),
        axis.title.y = element_markdown(size = 9, margin = margin(r = 0, b = 0)),
        axis.line.x = element_line(color = "black", linewidth = 0.7),
        axis.ticks.x = element_line(color = 'black', linewidth = .7),
        axis.ticks.length = unit(.35, "cm"),
        plot.margin = margin(1, 1, 1, 1, "cm"),
        legend.position = 'none',
        axis.text.x = element_text(size = 8),
        panel.spacing.x = unit(1, "lines")) +
  scale_y_continuous(breaks = seq(0, 60, by = 5),
                     limits = c(0, 60)) +
  scale_x_continuous(expand = c(0, 0),
                     limits = c(2009, 2022)) +
  facet_grid(County ~ ., scales = "free_y")

finalviz3
ggplotly(finalviz3)  
```

Page 2 {data-orientation=rows data-icon="fa-hashtag"}
==============================

Row {data-height=800} {data-width=300}
-----------------------------------------

### Chart A

```{r 3}
counties<-medexam %>%
  filter(Drug.Type =='All Drugs') %>%
  filter(Time.Measure == 'Year') %>%
  filter(Count.rate== 'Rate') 


counties$Time.Period <- as.numeric(counties$Time.Period)

overall_rate2 <- counties %>%
  group_by(County, Time.Period) %>% 
  summarize(Sum_Rate = sum(Rate))
counties <- counties %>%
  left_join(overall_rate2, by = "Time.Period")

overall_rate2<- overall_rate2[-287,]


my_color<-rep('gray',length(unique(overall_rate3$County)))
    names(my_color) <- unique(overall_rate3$County) 
    my_color['OREGON STATEWIDE'] <- 'black' 
    my_color['GILLIAM']<- '#FF9DA7'
    my_color['LANE']<- '#59A14F'
    my_color['MULTNOMAH']<- '#E15759'
    my_color['BAKER']<- '#4E79A7'
    my_color['LINN']<- '#F28E2B'
    my_color['KLAMATH']<- '#9C755F'

finalviz2<- ggplot(overall_rate3,
           aes(x = Time.Period, y = Sum_Rate, colour = County)) +
      geom_line(stat = 'identity') + 
      scale_color_manual(values=my_color) +
      labs(title="There are stark difference in overdose death rates <br /> among Oregon counties",
           subtitle = 'Rates include accidental and suicide overdose deaths',
           x     = '',
           y     = 'Rate per 100,000 deaths',
           caption = "Source: Oregon Prescribing Data Dashboard") +
  theme(plot.title= element_markdown(margin = margin(b=3),hjust=0, size = 15, face ='bold'),
  plot.subtitle= element_markdown(margin = margin(b=30),hjust=0, size = 12, face = 'italic'),
    panel.background = element_rect(fill='white',colour='white'),
    axis.ticks= element_blank(),
    panel.grid.major.y = element_line(color      = "grey80", 
                                              linewidth  = 0.5, 
                                              linetype   = "dashed"),
    plot.caption= element_text(hjust = 0.01,
                               size = 9,
                               margin=margin(t=0)),
    axis.line.x = element_line(color = "black", linewidth = 0.7),
    axis.ticks.x = element_line(color='black',linewidth = .7), 
    axis.ticks.length=unit(.35, "cm"), 
         plot.margin = margin(1, 1,1,1, "cm"),
         legend.position = 'none', 
         axis.title.y = element_markdown(size   = 9, 
                                                  vjust  = 1.05,
                                                  angle  = 360, 
                                                  margin = margin(r = -80,b=0)),) +
      scale_y_continuous(breaks = seq(0, 65, by = 5),
                         limits = c(0,65)) +
      scale_x_continuous(expand = c(0,0),
                         limits = c(2009,2022), 
                         breaks = seq(2010, 2022, by = 2))+ 
      annotate('text',
             x        = 2014,
             y        = 15,
             hjust    = .1,
             vjust    = 0,
             label    = 'Oregon Statewide',
             size     = 4,
             color    = 'black', 
             fontface = 'bold') 
             
ggplotly(finalviz2)
```

Row {data-height=800} {data-width=500}
-----------------------------------------
### Chart B

    
```


Page 3 {style="position:relative;" data-icon='fa-check'}
==============================

{style="height:30pc;"}
-----------------------------------------

### Chart A

```{r 4}
counties<-medexam %>%
  filter(Drug.Type =='All Drugs') %>%
  filter(Time.Measure == 'Year') %>%
  filter(Count.rate== 'Rate') 


counties$Time.Period <- as.numeric(counties$Time.Period)

overall_rate2 <- counties %>%
  group_by(County, Time.Period) %>% 
  summarize(Sum_Rate = sum(Rate))
counties <- counties %>%
  left_join(overall_rate2, by = "Time.Period")

overall_rate2<- overall_rate2[-287,]


my_color<-rep('gray',length(unique(overall_rate3$County)))
    names(my_color) <- unique(overall_rate3$County) 
    my_color['OREGON STATEWIDE'] <- 'black' 
    my_color['GILLIAM']<- '#FF9DA7'
    my_color['LANE']<- '#59A14F'
    my_color['MULTNOMAH']<- '#E15759'
    my_color['BAKER']<- '#4E79A7'
    my_color['LINN']<- '#F28E2B'
    my_color['KLAMATH']<- '#9C755F'

finalviz2<- ggplot(overall_rate3,
           aes(x = Time.Period, y = Sum_Rate, colour = County)) +
      geom_line(stat = 'identity') + 
      scale_color_manual(values=my_color) +
      labs(title="There are stark difference in overdose death rates <br /> among Oregon counties",
           subtitle = 'Rates include accidental and suicide overdose deaths',
           x     = '',
           y     = 'Rate per 100,000 deaths',
           caption = "Source: Oregon Prescribing Data Dashboard") +
  theme(plot.title= element_markdown(margin = margin(b=3),hjust=0, size = 15, face ='bold'),
  plot.subtitle= element_markdown(margin = margin(b=30),hjust=0, size = 12, face = 'italic'),
    panel.background = element_rect(fill='white',colour='white'),
    axis.ticks= element_blank(),
    panel.grid.major.y = element_line(color      = "grey80", 
                                              linewidth  = 0.5, 
                                              linetype   = "dashed"),
    plot.caption= element_text(hjust = 0.01,
                               size = 9,
                               margin=margin(t=0)),
    axis.line.x = element_line(color = "black", linewidth = 0.7),
    axis.ticks.x = element_line(color='black',linewidth = .7), 
    axis.ticks.length=unit(.35, "cm"), 
         plot.margin = margin(1, 1,1,1, "cm"),
         legend.position = 'none', 
         axis.title.y = element_markdown(size   = 9, 
                                                  vjust  = 1.05,
                                                  angle  = 360, 
                                                  margin = margin(r = -80,b=0)),) +
      scale_y_continuous(breaks = seq(0, 65, by = 5),
                         limits = c(0,65)) +
      scale_x_continuous(expand = c(0,0),
                         limits = c(2009,2022), 
                         breaks = seq(2010, 2022, by = 2))+ 
      annotate('text',
             x        = 2014,
             y        = 15,
             hjust    = .1,
             vjust    = 0,
             label    = 'Oregon Statewide',
             size     = 4,
             color    = 'black', 
             fontface = 'bold') 
             
ggplotly(finalviz2)
```

Column {style="height:100pc;"}
-----------------------------------------

### Chart B

```{r}
 
```



Page 4 {.storyboard}
==============================

### Final {data-commentary-width=400}


```{r}
rate<-medexam %>%
  filter(County == "OREGON STATEWIDE") %>%
  filter(Drug.Type =='All Drugs') %>%
  filter(Time.Measure == 'Year') %>%
  filter(Count.rate== 'Rate')


overall_rate <- rate %>%
  group_by(Time.Period) %>%
  summarize(Sum_Rate = sum(Rate))

rate <- rate %>%
  left_join(overall_rate, by = "Time.Period")

rate$Time.Period <- as.numeric(rate$Time.Period)

### 1st rendition 
viz1<-overall_rate3 %>% 
  filter(County == "OREGON STATEWIDE")

ggplot(viz1,
           aes(x = Time.Period, y = Sum_Rate)) +
      geom_line(stat = 'identity') + 
  labs(title = "Statewide overdose deaths continue to rise",
           subtitle = 'Rates double since 2019',
           x     = '',
           y     = 'Rate per 100,000 deaths', 
           caption = "Source: Oregon Prescribing Data Dashboard") + 
      theme(plot.title= element_markdown(margin = margin(b=3),hjust=0, size = 15, face ='bold'),
  plot.subtitle= element_markdown(margin = margin(b=30),hjust=0, size = 12, face='italic'),
            axis.title.y       = element_markdown(size   = 9, 
                                                  vjust  = 1.02,
                                                  angle  = 360, 
                                                  margin = margin(r = -80,b=-80)),
            panel.background   = element_blank(),
            panel.grid.major.y = element_line(color      = "grey80", 
                                              linewidth  = 0.5, 
                                              linetype   = "dotted"),
            axis.line.x        = element_line(colour='black'),
            axis.text.x        = element_text(margin=margin(t=0)),
            axis.ticks.x       = element_line(),
            axis.ticks.y       = element_blank(),
            axis.ticks.length  = unit(0.25, "cm"),
            plot.caption       = element_text(hjust = 0.01, 
                                              size  = 9,
                                              margin=margin(b=5)), 
            plot.margin = margin(1, 1,1,1, "cm"))+
      scale_y_continuous(breaks = seq(0, 50, by= 5),
                         limits = c(0,55)) +
      scale_x_continuous(expand = c(0,0),
                         limits = c(2009,2023))+
  geom_rect(xmin = 2020.3, xmax = 2022, ymin = 0, ymax = 50, fill = "#E15759", alpha = 0.05)+
  geom_segment(aes(x = 2021.2, y = 0, xend = 2021.2, yend = 50), linetype = "dashed", color = "black")+
  annotate('text',
             x        = 2020.65,
             y        = 50.5,
             hjust    = .1,
             vjust    = 0,
             label    = 'COVID-19\n Pandemic',
             size     = 3,
             color    = 'black')+
     annotate("segment", x = 2019, y = 10 , xend = 10, yend = 2021,
              arrow = arrow(type = "closed", length = unit(0.01, "npc")))+
           annotate("segment", x = 2020, y = 10, xend = 2021.1, yend=10,
         arrow = arrow(type = "closed", length = unit(0.01, "npc")))+ 
   annotate('text',
             x        = 2019,
             y        = 9.8,
             vjust    = 0,
             label    = 'Measure 110 goes\n into effect',
             size     = 3,
             color    = 'black')
 
```

****

Lots to say here. There is important

### Rendition 2 {data-commentary-width=300}

```{r}
viz1<- overall_rate3 %>% 
  filter(County == "OREGON STATEWIDE")

ggplot(viz1,
           aes(x = Time.Period, y = Sum_Rate)) +
      geom_line(stat = 'identity') + 
  labs(title = "Drug overdose deaths increasing in Oregon",
           subtitle = 'Especially since 2019',
           x     = '',
           y     = 'Rate per 100,000', 
           caption = "Source: Oregon Prescribing Data Dashboard") + 
      theme(plot.title         = element_markdown(margin = margin(b=10),
                                                  hjust  = 0),
            plot.subtitle      = element_markdown(margin = margin(b=35),
                                                  hjust  = 0, size = 8),
            axis.title.y       = element_markdown(size   = 9, 
                                                  vjust  = 1.025,
                                                  angle  = 360, 
                                                  margin = margin(r = -80,b=-60)),
            panel.background   = element_blank(),
            panel.grid.major.y = element_line(color      = "grey80", 
                                              linewidth  = 0.5, 
                                              linetype   = "dotted"),
            axis.line.x        = element_line(colour='black'),
            axis.text.x        = element_text(margin=margin(t=0)),
            axis.ticks.x       = element_line(),
            axis.ticks.y       = element_blank(),
            axis.ticks.length  = unit(0.25, "cm"),
            plot.caption       = element_text(hjust = 0.01, 
                                              size  = 9,
                                              margin=margin(t=0)), 
            plot.margin = margin(1, 1,1,1, "cm"))+
      scale_y_continuous(breaks = seq(0, 50, by= 5),
                         limits = c(0,50)) +
      scale_x_continuous(expand = c(0,0),
                         limits = c(2009,2022))


  
```

### Rendition 1 {data-commentary-width=300}
```{r}


image

```

****

Move along...

